[theme]
base = "light"
primaryColor = "#0f172a"
backgroundColor = "#f8fafc"
secondaryBackgroundColor = "#ffffff"
textColor = "#334155"
font = "sans serif"

[server]
headless = true
port = 8501
address = "localhost"
